Public Class ReporteClienteCartera
    Public Property Empresa As String
    Public Property Ruc As String
    Public Property RazonSocial As String
    Public Property Sector As String
    Public Property FechaAsignacion As String
    Public Property ModoPago As String
    Public Property LcSigic As Decimal
    Public Property FactSigic As Decimal
    Public Property LcDisponible As Decimal
    Public Property FechaApertura As String
    Public Property FechaExpiracion As String
    Public Property DiasPlazo As Integer
    Public Property CodigoEmpleado As Int64
    Public Property NombreRrvv As String
    Public Property AsignRrvv As String
    Public Property Sucursal As String
    Public Property Zona As String
    Public Property JefeVenta As String
    Public Property VentaSodimac As Decimal
    Public Property CostoSodimac As Decimal
    Public Property VentaMaestro As Decimal
    Public Property CostoMaestro As Decimal
    Public Property TotalVenta As Decimal
    Public Property TotalCosto As Decimal
    Public Property TotalContribucion As Decimal
    Public Property MargenContribucion As Decimal
    Public Property SubGerente As String
    Public Property FechaCreacion As String
    Public Property PorcentajeUtilizacion As Decimal
    Public Property EstadoLC As String
    Public Property EstadoCliente As String
    Public Property VentaTotalCredito As Decimal
    Public Property VentaTotalOracleCredito As Decimal
    Public Property VentaTotalOracleContado As Decimal
    Public Property VentaTotalContado As Decimal
    Public Property TotalVentasAvance As Decimal
End Class
