'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports WcfSerialization = System.Runtime.Serialization


''' <summary>
''' Data Contract Class - TablaGrupo
''' </summary>	
<WcfSerialization.DataContract([Namespace]:="http://Sodimac.VentaEmpresa.Model/2013/DCSodimac", Name:="TablaGrupo")> _
Partial Public Class TablaGrupo
    Private m_idTabGru As Integer
    Private m_nombreTabGru As String
    Private m_activoTabGru As Boolean

    <WcfSerialization.DataMember(Name:="IdTabGru", IsRequired:=False, Order:=0)> _
    Public Property IdTabGru() As Integer
        Get
            Return m_idTabGru
        End Get
        Set(value As Integer)
            m_idTabGru = value
        End Set
    End Property

    <WcfSerialization.DataMember(Name:="NombreTabGru", IsRequired:=False, Order:=1)> _
    Public Property NombreTabGru() As String
        Get
            Return m_nombreTabGru
        End Get
        Set(value As String)
            m_nombreTabGru = value
        End Set
    End Property

    <WcfSerialization.DataMember(Name:="ActivoTabGru", IsRequired:=False, Order:=2)> _
    Public Property ActivoTabGru() As Boolean
        Get
            Return m_activoTabGru
        End Get
        Set(value As Boolean)
            m_activoTabGru = value
        End Set
    End Property
End Class



