'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.6387
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization

Namespace Sodimac.VentaEmpresa.Web.Mvc.ServicioComun

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ListaTablaGeneral", [Namespace]:="http://Sodimac.VentaEmpresa.Model/2013/DCSodimac", ItemName:="TablaGeneral")> _
    Public Class ListaTablaGeneral
        Inherits System.Collections.Generic.List(Of Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.TablaGeneral)
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="TablaGeneral", [Namespace]:="http://Sodimac.VentaEmpresa.Model/2013/DCSodimac")> _
    Partial Public Class TablaGeneral
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private IdTabGenField As Integer

        Private TablaGrupoField As Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.TablaGrupo

        Private OrdenTabGenField As Integer

        Private DescripcionTabGenField As String

        Private ActivoTabGenField As Boolean

        Private DescripcionLargaTabGenField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property IdTabGen() As Integer
            Get
                Return Me.IdTabGenField
            End Get
            Set(value As Integer)
                Me.IdTabGenField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property TablaGrupo() As Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.TablaGrupo
            Get
                Return Me.TablaGrupoField
            End Get
            Set(value As Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.TablaGrupo)
                Me.TablaGrupoField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)> _
        Public Property OrdenTabGen() As Integer
            Get
                Return Me.OrdenTabGenField
            End Get
            Set(value As Integer)
                Me.OrdenTabGenField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)> _
        Public Property DescripcionTabGen() As String
            Get
                Return Me.DescripcionTabGenField
            End Get
            Set(value As String)
                Me.DescripcionTabGenField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)> _
        Public Property ActivoTabGen() As Boolean
            Get
                Return Me.ActivoTabGenField
            End Get
            Set(value As Boolean)
                Me.ActivoTabGenField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)> _
        Public Property DescripcionLargaTabGen() As String
            Get
                Return Me.DescripcionLargaTabGenField
            End Get
            Set(value As String)
                Me.DescripcionLargaTabGenField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="TablaGrupo", [Namespace]:="http://Sodimac.VentaEmpresa.Model/2013/DCSodimac")> _
    Partial Public Class TablaGrupo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private IdTabGruField As Integer

        Private NombreTabGruField As String

        Private ActivoTabGruField As Boolean

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property IdTabGru() As Integer
            Get
                Return Me.IdTabGruField
            End Get
            Set(value As Integer)
                Me.IdTabGruField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property NombreTabGru() As String
            Get
                Return Me.NombreTabGruField
            End Get
            Set(value As String)
                Me.NombreTabGruField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)> _
        Public Property ActivoTabGru() As Boolean
            Get
                Return Me.ActivoTabGruField
            End Get
            Set(value As Boolean)
                Me.ActivoTabGruField = value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute(Name:="Error", [Namespace]:="http://Sodimac.VentaEmpresa.Model/2013/DCSodimac")> _
    Partial Public Class [Error]
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject

        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        Private GUIDField As System.Guid

        Private MensajeField As String

        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set(value As System.Runtime.Serialization.ExtensionDataObject)
                Me.extensionDataField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property GUID() As System.Guid
            Get
                Return Me.GUIDField
            End Get
            Set(value As System.Guid)
                Me.GUIDField = value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()> _
        Public Property Mensaje() As String
            Get
                Return Me.MensajeField
            End Get
            Set(value As String)
                Me.MensajeField = value
            End Set
        End Property
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Sodimac.PLE.Web.Mvc.ServicioComun.IServicioComunSoap")> _
    Public Interface IServicioComunSoap

        <System.ServiceModel.OperationContractAttribute(Action:="http://Sodimac.VentaEmpresa.Model/2013/SCSodimacPLEComun/ServicioComun/ListaTablaGeneral", ReplyAction:="http://tempuri.org/IServicioComunSoap/ListarTablaGeneralResponse"), _
         System.ServiceModel.FaultContractAttribute(GetType(Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.[Error]), Action:="http://tempuri.org/IServicioComunSoap/ListarTablaGeneralErrorFault", Name:="Error", [Namespace]:="http://Sodimac.VentaEmpresa.Model/2013/DCSodimac")> _
        Function ListarTablaGeneral(ByVal idTabGru As Integer, ByVal descripcionLargaTabGen As String) As Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.ListaTablaGeneral
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface IServicioComunSoapChannel
        Inherits Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.IServicioComunSoap, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Partial Public Class ServicioComunSoapClient
        Inherits System.ServiceModel.ClientBase(Of Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.IServicioComunSoap)
        Implements Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.IServicioComunSoap

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        Public Function ListarTablaGeneral(ByVal idTabGru As Integer, ByVal descripcionLargaTabGen As String) As Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.ListaTablaGeneral Implements Sodimac.VentaEmpresa.Web.Mvc.ServicioComun.IServicioComunSoap.ListarTablaGeneral
            Return MyBase.Channel.ListarTablaGeneral(idTabGru, descripcionLargaTabGen)
        End Function
    End Class
End Namespace
