'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Validaciones
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sodimac.VentaEmpresa.Validation.Validaciones", GetType(Validaciones).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este campo es obligatorio.
        '''</summary>
        Public Shared ReadOnly Property CampoRequerido() As String
            Get
                Return ResourceManager.GetString("CampoRequerido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Requerido.
        '''</summary>
        Public Shared ReadOnly Property CampoRequeridoCustom() As String
            Get
                Return ResourceManager.GetString("CampoRequeridoCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formato de correo electronico incorrecto.
        '''</summary>
        Public Shared ReadOnly Property EmailCustom() As String
            Get
                Return ResourceManager.GetString("EmailCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formato para Fecha Incorrecto.
        '''</summary>
        Public Shared ReadOnly Property FormatoFechaIncorrecto() As String
            Get
                Return ResourceManager.GetString("FormatoFechaIncorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formato Incorrecto.
        '''</summary>
        Public Shared ReadOnly Property FormatoIncorrecto() As String
            Get
                Return ResourceManager.GetString("FormatoIncorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formato para {0} incorrecto.
        '''</summary>
        Public Shared ReadOnly Property FormatoIncorrectoCustom() As String
            Get
                Return ResourceManager.GetString("FormatoIncorrectoCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este campo debe tener entre {2} y {1} caracteres.
        '''</summary>
        Public Shared ReadOnly Property LongitudCadena() As String
            Get
                Return ResourceManager.GetString("LongitudCadena", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo {0} debe tener entre {2} y {1} caracteres.
        '''</summary>
        Public Shared ReadOnly Property LongitudCadenaCustom() As String
            Get
                Return ResourceManager.GetString("LongitudCadenaCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo {0} debe tener {1} caracteres.
        '''</summary>
        Public Shared ReadOnly Property LongitudExacta() As String
            Get
                Return ResourceManager.GetString("LongitudExacta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor para {0} debe estar entre {1} y {2}.
        '''</summary>
        Public Shared ReadOnly Property RangeDateWeb() As String
            Get
                Return ResourceManager.GetString("RangeDateWeb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifique los datos, gracias..
        '''</summary>
        Public Shared ReadOnly Property RegistroError() As String
            Get
                Return ResourceManager.GetString("RegistroError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se registro correctamente, gracias..
        '''</summary>
        Public Shared ReadOnly Property RegistroOk() As String
            Get
                Return ResourceManager.GetString("RegistroOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione un item.
        '''</summary>
        Public Shared ReadOnly Property SeleccionNecesaria() As String
            Get
                Return ResourceManager.GetString("SeleccionNecesaria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El formato para números telefónicos es incorrecto.
        '''</summary>
        Public Shared ReadOnly Property SoloCaracteresTelefono() As String
            Get
                Return ResourceManager.GetString("SoloCaracteresTelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo solo admite decimales.
        '''</summary>
        Public Shared ReadOnly Property SoloDecimal() As String
            Get
                Return ResourceManager.GetString("SoloDecimal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo {0} sólo admite letras.
        '''</summary>
        Public Shared ReadOnly Property SoloLetrasCustom() As String
            Get
                Return ResourceManager.GetString("SoloLetrasCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo solo admite números.
        '''</summary>
        Public Shared ReadOnly Property SoloNumeros() As String
            Get
                Return ResourceManager.GetString("SoloNumeros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo {0} sólo admite números.
        '''</summary>
        Public Shared ReadOnly Property SoloNumerosCustom() As String
            Get
                Return ResourceManager.GetString("SoloNumerosCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor ingresado es incorrecto.
        '''</summary>
        Public Shared ReadOnly Property ValorIncorrecto() As String
            Get
                Return ResourceManager.GetString("ValorIncorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EL valor ingresado para {0} es incorrecto.
        '''</summary>
        Public Shared ReadOnly Property ValorIncorrectoCustom() As String
            Get
                Return ResourceManager.GetString("ValorIncorrectoCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formato incorrecto.
        '''</summary>
        Public Shared ReadOnly Property WebCustom() As String
            Get
                Return ResourceManager.GetString("WebCustom", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
